export const fourpxInventoryMap = new Map([
	["英国路腾仓", "GBLTNA"],
	["英国莱切斯特仓", "GBLONA"],
	["比利时列日仓", "BELGGB"],
	["比利时监管仓", "BELGGA"],
	["美国洛杉矶仓", "USLAXA"],
	["美国洛杉矶2仓", "USLAXB"],
	["美国洛杉矶3仓", "USLAXC"],
	["美国洛杉矶5仓", "USLAJA"],
	["美国洛杉矶6仓", "USLAXF"],
	["美国新泽西1仓", "USNYCA"],
	["美国新泽西2仓", "USNJCB"],
	["美国休斯顿仓", "USHOUA"],
	["美国萨凡纳仓", "USSAVA"],
	["澳洲悉尼仓", "AUSYDA"],
	["澳洲墨尔本二仓", "AUMELB"],
	["德国法兰克福1仓", "DEFRAA"],
	["德国法兰克福2仓", "DEFRAB"],
	["德国法兰克福3仓", "DEFRAC"],
	["德国法兰克福4仓", "DEFRAD"],
	["德国不来梅仓", "DEBREA"],
	["波兰1仓", "PLSLBB"],
	["波兰2仓", "PLROKB"],
	["波兰3仓", "PLROKC"],
	["捷克布拉格仓", "CZPRGA"],
	["香港仓", "CNHKGB"],
	["加拿大温哥华仓", "CAMSGA"],
	["日本大阪仓", "JPOSAA"],
	["法国巴黎1仓", "FRCDGA"],
	["法国巴黎2仓", "FRCDGB"],
	["西班牙马德里仓", "ESMADA"],
	["墨西哥云仓", "MXTEPA"],
]);

export const internalInventoryTo4pxMap = new Map([
	["英国海外仓", ["GBLTNA", "GBLONA"]],
	[
		"USA海外仓",
		[
			"USLAXA",
			"USLAXB",
			"USLAXC",
			"USLAJA",
			"USLAXF",
			"USNYCA",
			"USNJCB",
			"USHOUA",
			"USSAVA",
		],
	],
	["澳洲海外仓", ["AUSYDA", "AUMELB"]],
	["DE海外仓", ["DEFRAA", "DEFRAB", "DEFRAC", "DEFRAD", "DEBREA"]],
	["加拿大海外仓", ["CAMSGA"]],
	["墨西哥海外仓", ["MXTEPA"]],
]);
