import "./globals.css";
import type { Metadata } from "next";
import AppWrapper from "@/components/appWrapper/AppWrapper";

export async function generateMetadata(props: any): Promise<Metadata> {
	return {
		title: "Create Next App",
		description: "Generated by create next app",
	};
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html>
			<body>
				<AppWrapper>{children}</AppWrapper>
			</body>
		</html>
	);
}
